Repository Blackraven93/git-collaboration, pull requests merged in 2021-12, with the labels that each got.

#2 Won seok
  Won_Seok/01_calculate/calculate.js
  Won_Seok/02/index.js
  Won_Seok/03/index.js
Labels: enhancement, good first issue

#4 [계산식 기능] 김태원 미션 제출합니다.
  calculate.html
  calculate.js
Labels: documentation, enhancement

#7 [계산식 기능] 김태원 미션 제출합니다.
  김태원/README.md
  김태원/calculate.html
  김태원/calculate.js
Labels: documentation, enhancement

#8 Docs: make calculate 과제제출
  Won_Seok/01_calculate/calculate.js
  Won_Seok/02/index.js
  Won_Seok/03/index.js
  calculate.js
  김태원/README.md
  김태원/calculate.html
  김태원/calculate.js
  전다원/calculate.html
  전다원/calculate.js
  최재훈/calculate.html
  최재훈/calculate.js
Labels: documentation, enhancement

#12 [계산식 기능] 김태원 미션 제출합니다.
  README.md
  Won_Seok/01_calculate/calculate.js
  calculate.html
  calculate.js
  김태원/calculate.js
  최재훈/calculate.js
Labels: duplicate

#17 feat : first try
  주산들/calculater.js
  주산들/index.html
Labels: question

#19 feat: Edit comments
  Won_Seok/01_calculate/calculate.js
Labels: little fix

#22 feat : change parameter and execute function
  전다원/calculate.js
Labels: enhancement

#23 feat : pull by blackraven and push again 13:52pm
  전다원/calculate.js
Labels: help wanted

#24 [새 계산식]김태원 새 미션 제출합니다.
  README.md
  김태원 새 계산식/README.md
  김태원 새 계산식/carculate.html
  김태원 새 계산식/carculate.js
Labels: enhancement

#27 [새 계산식]김태원 새 미션 제출합니다.
  김태원 새 계산식/carculate.js
Labels: bug
